name: release
on:
  push:
    branches:
      - "main"

jobs:
  build:
    if: github.repository_owner == 'flybywiresim'
    runs-on: windows-latest
    env:
      RELEASE_ZIP_NAME: FBW-local-api.zip
    steps:
      - name: Checkout source
        uses: actions/checkout@v3
      - name: Build Local API
        run: |
          npm install
          npm run build:exec
      - name: Build ZIP File
        run: |
          Compress-Archive -Path .\dist\local-server.exe, .\apps\server\src\config\properties.json, .\node_modules\pdf-to-printer\dist\SumatraPDF.exe -DestinationPath ${{ env.RELEASE_ZIP_NAME }}
      - name: Create and Publish Release
        id: create_release
        uses: softprops/action-gh-release@v1
        with:
          files: |
          ${ env.RELEASE_ZIP_NAME }
          LICENSE
